---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: DynaKube
  namespace: dynatrace
spec:
  dependsOn:
    - name: addons-partner
  path: "./eks-anywhere-common/Addons/Partner/dynatrace/dynatrace-dynakube"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
  postBuild:
    substitute:
      # api url for dynatrace environment 
      apiurl: "https://fjy55252.sprint.dynatracelabs.com/api"
      # name of secret containing tokens
      dynatracesecretname: "dt-secret"
      # name of cluster to be listed in Dynatrace
      clusternamedt: "testcluster1"
    # substituteFrom:
    # - kind: ConfigMap
    #   name: dynatrace-variables # Provides apiurl, dynatracesecretname, clusternamedt
---
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  # name: "test-cluster-no-substitution"
  name: ${clusternamedt}
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: ${apiurl}
  tokens: ${dynatracesecretname}
  # apiUrl: "https://fjy55252.sprint.dynatracelabs.com/api"
  # tokens: "dt-secret"  
  skipCertCheck: false
  oneAgent:
    classicFullStack:
      # image: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      env:
        - name: ONEAGENT_ENABLE_VOLUME_STORAGE
          value: "true"
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    #image: ""
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
